#!/bin/sh
PLUGIN_NAME=transmission
WORKDIR=$(dirname $0)

TOOLCHAIN_DIR=${WORKDIR}/dns325_GPL

MKAPKG_DIR=${WORKDIR}/"ShareCenter Add-On SDK_v2.0_12192011"
MKAPKG="$MKAPKG_DIR/mkapkg"

WORKDIR_LIB="$WORKDIR/lib"
WORKDIR_INC="$WORKDIR/include"
WORKDIR_OUT="$WORKDIR/$PLUGIN_NAME"
WORKDIR_TMPL="$WORKDIR/templates"
if [ -x "$MKAPKG" ]; then chmod +x "$MKAPKG"; fi
cd ${WORKDIR_OUT}
"$MKAPKG" -m DNS-325
